# Generated by Django 6.1.1 on 2026-09-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size_kb', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('word_count', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('status_label', models.CharField(default='Average', max_length=50)),
                ('career_field', models.CharField(default='Software Engineering', max_length=100)),
                ('skills', models.JSONField(default=list)),
                ('sections_found', models.JSONField(default=dict)),
                ('missing_sections', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('raw_text', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
